### ISSUE TITLE
timing atExit no longer working for call statement

### ISSUE THREAD

**Issue by inchl** [theNestruo/z80-asm-meter-vscode#124]
Hi, found an bug in the exit timing.

jr z,label
jr label   -> timing = 21 (correct)

call z,$
call $   -> timing = 36/29 (incorrect, should be just 29)

call z,$
call z,$
call z,$  -> timing = 54/33 (incorrect, should be just 40)

The icon for exit timing is nice and intuitive for what it stands for. However, sometimes I get the icon and two values for timing. Difficult to understand what that means (think its even incorrect to show two).

**Comment by theNestruo** [comment]
When "timing at exit" is enabled, the latest instruction, if conditional, is considered taken, and the previous instructions are considered not taken when they are either conditional JP, JR, or RET, but retain the two timing if they are conditional CALL.

The rationale behind that is that the conditional JP, JR, or RET instructions must have been not taken to reach the last selected instruction, but a conditional CALL may have been invoked or may have not:
```
ld a, (JIFFY)
and 1
call z, ROUTINE_1
call ROUTINE_2 ; this line is reached regardless ROUTINE_1 has (or has not) been called
```

Anyway, I think that "timing at exit" is too restrictively applied: it is only used if the last instruction is JP, JR, or RET, but it would make sense to be used regardless the type of the last instruction, as you may be trying to meter the timing up to one particular point of the code (even if is not the end of the routine).

**Comment by inchl** [comment]
> The rationale behind that is that the conditional JP, JR, or RET instructions must have been not taken to reach the last selected instruction, but a conditional CALL may have been invoked or may have not:

Yes. I understand now. Correct me if I wrong. The first of the two is all call conditions are met, and the second non is met, except for the last one if it was the last selected instruction. I was confused because that timing atExit icon wasn't displayed.
Still when having two statement selected (2x call z,0) should display: 36 for the first and 11+18=29 for the second. That second value should be prefixed with that atExit timing icon. If the atExit timing is not used by the developer the values should be: 36 / 22 (all taken/ non taken)

> Anyway, I think that "timing at exit" is too restrictively applied: it is only used if the last instruction is JP, JR, or RET, but it would make sense to be used regardless the type of the last instruction, as you may be trying to meter the timing up to one particular point of the code (even if is not the end of the routine).

If the last statement is a conditional one, then the developer selected the text block until that line on purpose. The timing of that last statement is with a condition that is met. Note that the selected textblock must end at the same line as that statement. If the selected text also includes that \n character beyond the last statement, the atExit timing should be different (currently it is the same).

**Comment by theNestruo** [comment]
> I was confused because that timing atExit icon wasn't displayed.

That's because, currently, the _atExit_ is only applied when the last instruction is JP/JR/RET.

> Note that the selected textblock must end at the same line as that statement. If the selected text also includes that \n character beyond the last statement, the atExit timing should be different (currently it is the same).

I'm not sure I understand your proposal here. Currently, selection is cleaned-up and trimmed, and calculations are applied to the detected instructions. The last instruction selected is the same regardless you include the line break, comment lines after the instruction, empty lines, etc.

**Comment by inchl** [comment]
> I'm not sure I understand your proposal here. Currently, selection is cleaned-up and trimmed, and calculations are applied to the detected instructions. The last instruction selected is the same regardless you include the line break, comment lines after the instruction, empty lines, etc.

I think you should ignore my request :-)....  Currently I am working on a game and doing some verification on the expected timing and what your tool is presenting. I could 'hear!' that the timing is incorrect because the samples being played in the game are having a noisy sound in them. However... after some investigation I concluded that the tool was in fact correct and I messed up somewhere else in the code.

I have an other request, but I will post it as another issue.

**Comment by theNestruo** [comment]
> However... after some investigation I concluded that the tool was in fact correct and I messed up somewhere else in the code.

Ok! Good to know :) I'll close this issue and take a look at the other issues/requests!

**Comment by theNestruo** [comment]
> However if I want to know the timing at point X, the expected timing for me would be just 34.

If the `call m,label2` were a `jp m,label2`, selecting up to X, the timing "at exit" (i.e.: when the routine ends because the jump is taken) would be `x 34/27`. The two values represent whether the `call m,label1` was takend and not taken.

If the extension is changed to meter "at exit" when the last selected instruction is a `call`, then you will be losing the `41/27` timing.

I think there are two separate improvements to be done:
- Timing at exit (as currently implemented, to meter execution flows of entire routiens) *and* "timing up to the selected instruction" (not implemented yet, to meter timing to reach a particular instruction)
- Show two or three timing algorithms at the same time: _default+atExit_, _default+upToHere_, _default+atExit+upToHere_

I think that would cover every possible use case without causing configuration hell.

> Will leave you alone for a few days because posting more issues about this :-)

No problem, as I will be away from keyboard a couple of weeks starting tomorrow! :_D I won't be able to code (and to answer issues), but I'll probably think about this at some point ^_^

> Again, amazing tool! Thank you.

Thank you for your reports. Your original proposal of "timings at exit" is indeed a great and useful improvement, and "forced" me to refactor the code (so REPT could be implemented, etc.). Everyone wins!

**Comment by theNestruo** [comment]
## Proposal

### "Timing modes" and configuration

* ~~`z80-asm-meter.timings.atExit`~~: Deprecated. Set `"z80-asm-meter.timings.mode"` to `"atExit"` instead.

* `z80-asm-meter.timings.mode`: Enables alternative total timing calculation modes when the selected code block contains two or more instructions.

    * `default` (default): Disables alternative total timing calculations; timings are simply added.
    * `flow`: Measures the timings of any selected conditional `JP`, `JR` or `RET` instruction as _not taken_. Total timings will show the timing of the execution flow through the selection.
    * `atExit`: Same as `flow` but, if the selection ends with a conditional `JP`, `JR` or `RET` instruction, measures this last conditional instruction as _taken_ (reverts to `flow` mode otherwise). Total timing will show the execution flow to the selected exit point. Therefore, allows metering best and worse case timings of routines by selecting the code up to the different exit points.
    * `atExitOrCall`: Same as `atExit`, but the logic also applies to the last conditional instruction if it is a conditional `CALL` instruction.
    * `flowAndAtExit`: Same as `flow` but, if the selection ends with a conditional `JP`, `JR` or `RET` instruction, also shows the timings using the `atExit` mode.
    * `flowAndAtExitOrCall`: Same as `flow` but, if the selection ends with a conditional `CALL`, `JP`, `JR` or `RET` instruction, also shows the timings using the `atExitOrCall` mode.

### Icons

For the [product icons](https://code.visualstudio.com/api/references/icons-in-labels) to be used to decorate alternative total timings in the status bar, I'm thinking about using:

* `flow`: _debug-step-over_ (or maybe _debug-step-into_),
* `atExit`: _debug-step-out_

![image](https://github.com/theNestruo/z80-asm-meter-vscode/assets/12213477/df81b6ec-639b-4588-b8d8-10c6ca5f2493)

(Note: Current version is using _debug-step-into_.)

---

What do you think?

**Comment by inchl** [comment]
Al lot of different ways to measure code flow. Maybe we should discuss this online via teamviewer? It might help if I show you how I use your tool in our current project.

**Comment by theNestruo** [comment]
Actually, there are not so many ways:
![image](https://github.com/theNestruo/z80-asm-meter-vscode/assets/12213477/ffb8d404-5691-405d-a1ed-0235097b017e)
- Addition of the timings of the invidiaul instructions (`23/18`)
- Execution flow (`step-over 18`)
- Timing at exit point (`step-out 23`)

And, depending on the selection, no all of them are available:
- Example 1:
  ![image](https://github.com/theNestruo/z80-asm-meter-vscode/assets/12213477/9931b682-ff59-4e89-8ef6-8c401d07b2c3)
  (_Timing at exit point_ is not available because the selection does not end with any jump/ret instruction)
- Example 2:
  ![image](https://github.com/theNestruo/z80-asm-meter-vscode/assets/12213477/791fe2e8-3d9f-4504-8fa8-942d3d113dae)
  (_Execution flow_ is not available because the selection ends with an unconditional jump/ret instruction. There is now way for the execution to continue below the selection)
- Example 3:
  ![image](https://github.com/theNestruo/z80-asm-meter-vscode/assets/12213477/3b11f934-8d68-48c1-9fea-4c6cd83a0554)
  (Neither _Timing at exit point_ nor _Execution flow_ are available because the selection contains an unconditional jump/ret instruction. It is not a single routine so it makes no sense to use any of them)

My proposal had many variations because, despite there are only three metering modes, I was considering combinations of how to show them. But after seeing it in action, having more than one in the statur bar is not as obtrusive as I originally though (see the examples above), so:
- `none`: do not use "advanced" timing modes.
- `showAll` (see the examples above): show all the timings mode that can be applied to the selection.
- `showOne` (to save status bar space): chooses the most specific timing mode that can be applied, in this order: _Timing at exit point_, _Execution flow_, default timing.

The thing that most confuses me is the expectations of timings mode when there are conditional call instructions: if they should be considered exit points (as your examples seems to imply) or not, and if that should be a setting (as most of the time they won't be exit points).

I mean: the only reason for a call instruction to be an exit point is when the called routine manipulates the stack to skip the caller function (i.e.: ends with `pop hl : ret` or similar constructions), but I think this is a rare case...

Yes, it may be useful to use teamviewer/discord/skype to clarify the issues with the call statements!

**Comment by inchl** [comment]
> 
> Yes, it may be useful to use teamviewer/discord/skype to clarify the
> issues with the call statements!
> 
You can contact me via whatsapp (+31652477306).

Stephan

**Comment by theNestruo** [comment]
I'm old fashioned and don't have whatsapp :_D. Please drop me an email: theNestruo at gmail dot com

**Comment by theNestruo** [comment]
For our live session, please use the version [4.3.0-RC1](https://github.com/theNestruo/z80-asm-meter-vscode/releases/tag/4.3.0-RC-1) and set `"z80-asm-meter.timings.mode": "all"`.
That will use the latest version of the total timings calculation modes and also will show all of them at the same time (it makes easier to check what is happening under the hood).

**Comment by inchl** [comment]
I noticed that the presentation is different between the following two situations. The  measured ts is correct, so its just userinterface.

situation#1
nop
call	p,label

situation#2
call	p,label

The first example shows >23/16 ^23 and the second one shows: 18/11. Would be nice if the second one also used the same format as the first one: >18/11 ^18
Don't know if its on purpose or not. If so, then ignore this post.

> and ^ are the specific icons you used.

**Comment by theNestruo** [comment]
Hi!

> Don't know if its on purpose or not. If so, then ignore this post.

Yes, it was intentional to prevent excessive noise when only one line is selected. Total timings calculation modes only apply when there are at least 2 instructions selected.

I'm adding a setting to allow changing this threshold :)
