### ISSUE TITLE
ds 0 is timed as '5'

### ISSUE THREAD

**Issue by inchl** [theNestruo/z80-asm-meter-vscode#125]
Currently the 'ds 0' statement from glass is timed as 5.
I fixed it by defining an empty macro for that statement, so not a bug, but maybe better to ignore ds-statements from timing analysis.

```
    "z80-asm-meter.macros": [   
        {
            "name": "ds 0",
            "instructions": []
        }
    ],
```

**Comment by theNestruo** [comment]
It is a bug.
Metering `ds` directives as instructions was introduced here https://github.com/theNestruo/z80-asm-meter-vscode/issues/40, but with the default configuration it should not be considered an instruction.

It seems that the default value of `z80-asm-meter.directivesAsInstructions` is `defs` (instead of `none`, as documented). But after setting it to `none` there is some thing wrong when parsing directives. Let me have a look...

**Comment by theNestruo** [comment]
I have fixed the default value of the `z80-asm-meter.directivesAsInstructions` setting in the version 4.2.0, as well as other issues related with configuration changes not being applied.
