### ISSUE TITLE
Halves of index registers

### ISSUE THREAD

**Issue by ammehet** [theNestruo/z80-asm-meter-vscode#17]
Instructions like `LD XL,n` and `LD YH,r` are not recognized while `OR XL` is processed correctly.
Also, `LD IXL,n` is recognized, but the calculated length is 2 bytes instead of 3.

**Comment by theNestruo** [comment]
Thanks for the report!
Both problems will be fixed in the next version.

It seems that instructions using any half (such as `OR IXp`) accepted multiple syntax for the register, while instructions using an specific half (such as `LD IXl,n`) were requiring a verbatim match (hence `IXL` was recognized but was not).

The size issue comes from the source Z80 instruction set data; I'll report it to the page maintainer.

**Comment by ammehet** [comment]
`DEC L` shows 2 bytes instead of 1.

**Comment by theNestruo** [comment]
`LD HL,(NN)` and `IN F,(C)` were also wrong.
They are all fixed now; both in this extension and in the [Z80 Instruction Set](http://map.grauw.nl/resources/z80instr.php) source data.
Thanks!
