### ISSUE TITLE
strange behaviour on labels with length = 1

### ISSUE THREAD

**Issue by inchl** [theNestruo/z80-asm-meter-vscode#181]
jp x   -> shown as 11
jp d   -> not shown (not detected as opcode)

jr opcode same issue... (other opcodes not tested for bug)

**Comment by theNestruo** [comment]
This was somehow intentional because those label name are problematic:

```asm
B: equ 42
LD A, B ; Is this "LD A, B" or is it "LD A, 42"?
```

But I can relax a little bit the constrains...

**Comment by inchl** [comment]
yes, I get now.... make sense why this is an issue. One chr labels isn't something I use btw, I ran into this when I did an accidental typo.

ld a,b -> TS = 5 (b is register)
ld a,bc -> TS = 8 (b must be an equ value)
jp b -> TS = 11 (b must be an equ value)
jr b -> TS = 13 (b must be an equ value) 
jp h -> TS = 11 (h must be an equ value)
call b -> TS = 18 (b must be an equ value)
call bc -> TS = 18 (bc must be an equ value)

remains these two:
jp hl
jp (hl)
are these the same or not? If not then 1e = 11 and 2nd = 5 otherwise 1e = 2nd = 5

Or just leave the whole thing as is.... one chr labels are stupid anyways.

**Comment by theNestruo** [comment]
> remains these two:
> jp hl
> jp (hl)
> are these the same or not? If not then 1e = 11 and 2nd = 5 otherwise 1e = 2nd = 5

`JP HL` should be an alias for `JP (HL)` only when `z80-asm-meter.syntaxFeature.fakeInstructions` is enabled (5 clock cycles), and it should be recognized as `JP nn` otherwise (11 clock cycles).

However, in the current version (5.6.4, published yesterday), is always recognized as `JP nn`. I'm already fixing that, but it seems that SjASMPlus fake instructions support is not working as expected. I'm already working on it.

**Comment by theNestruo** [comment]
I just fixed the SjASMPlus fake instructions problems (version 5.6.5 onwards).

Thanks for your report!
