### ISSUE TITLE
Use of ds (or defs) for nop(s)

### ISSUE THREAD

**Issue by gougoutt** [theNestruo/z80-asm-meter-vscode#40]
It is quite common in CPC coding to use ```ds``` of ```defs``` as an equivalent for multiple ```nop``` for synchronization purpose. For example, in the case of a 64 μs rasterline, we may need additional ```nop``` to reach the 64 μs.
See the code sample below, where we add 32 ```nop``` with ```ds 32```

```
; each line is 64 μs which is 64 nops (1 nop = 1 μs)
LineLoop:
ld a,(hl)
cp #ff
jp z,WaitVBL
; change border color  
; #10 is select border in gate array (penr control bits)
ld c,#10          
out (c),c          
out (c),a         
; change pen 0 color  
ld c,#0            
out (c),c         
out (c),a         
inc hl
; we need 32 additional nops for a 64 nops loop            
ds 32             
jp LineLoop
```

Alternative to ```ds n```:
```
ds n,0
defs n
defs n,0
```

**Comment by theNestruo** [comment]
Hi gougoutt!

I find some problems trying to support that _sacrilegious_ syntax... ;)

- I need to value (the `32` in your example) to know the repetition count of the instruction. Ok, this is achievable.
- The parameter may be an expression (such as `ds 32 - 5 ; (up to 32, but we already had 5 nops)`).
- Even more, the expression may have symbolic constants, or non-constant values such as $ (from my own code: `ds ($ OR $1fff) -$ +1, $ff ; (8kB boundary to allow 8kB or 24kB ROMs)`). This is definitely out of the scope of this extension.

Also:

- The extension parses instructions, but does not parse bytecode. It should be extended to parse bytecode. But with the current internal tables is easy to support bytes such as `#00` (NOP) or `#ff` (RST 38H)... but not bytes such as `#80` (because all the `ADD A,r` instructions are translated to the literal `80+r`, not to their individual bytecodes). Ok, I think I can solve this too.
- And, again, this parameter can be a symbolic constant (such as `BYTECODE_FOR_NOP`).

Let me think about it, but probably only the first point will be supported (direct value as the first parameter of the ds/defs directive). Would that be enough?

**Comment by gougoutt** [comment]
Hi Néstor,

I have only seen so far these four syntaxes for the specific use case of synchronisation:
```
ds n
ds n,0
defs n
defs n,0
```

I am quite new to z80 coding and right now I am reading some demo related z80 code.
If I find other uses of ds/defs I will let you know ;)

Thank you.

Sebastien

**Comment by theNestruo** [comment]
Hi, Sebastien!

Support for `ds n`, `ds n,b`, `defs n`, and `defs n,b` added (without mathematical expressions for the moment).

Would you mind testing the _1.5.0-nightly_ build ("Actions" > "NPM CI" > latest > "Artifacts") a bit before the release?

Thanks!

**Comment by gougoutt** [comment]
Hi Néstor,

I would be happy to test it. I can't find the release however in the NPM CI workflow.
I am new to Github so definitely not an expert.

Sébastien

**Comment by theNestruo** [comment]
No problem :)

Here's the link: https://github.com/theNestruo/z80-asm-meter-vscode/suites/1585184548/artifacts/28733541
And, in case the link does not work (I'm not an expert either, so I'm not sure if the link is stable), here is as an attachment: [z80-asm-meter-1.5.0-nightly.zip](https://github.com/theNestruo/z80-asm-meter-vscode/files/5620651/z80-asm-meter-1.5.0-nightly.zip)
It contains the extension as an VSIX file that can be installed in VSCode using the ">Extensions: install from VSIX.." command.

Thanks again!
Néstor.

**Comment by gougoutt** [comment]
Hi Néstor,

I tested and it works for the following use cases:
```
ds n
ds n,v
defs n
defs n,v
```

Where ```n``` (resp. ```v```) is a decimal value or a hexadecimal value starting with ```0x``` or ending with ```h```.

I noticed that when ```n``` or ```v``` is:
- Binary value starting with ```%```
- Octal value starting with ```@```
- Hexadecimal value starting with ```#``` or ```&```

It sets the NOP and bytes counter to zero.

It is be a side effet that you don't want since these binary, octal and hexadecimal notations are correctly handled for other instructions such as ```ld```, ```cp```, etc. For example:
```defs 32,#0``` : 0 NOP, 0 byte
```ld c,#10``` : 2 NOP, 2 bytes

**Comment by theNestruo** [comment]
Thanks!

I've just added support for those numeric syntaxes (%, @, # and &). I'm not used to them, so I completely forgot about them.
Actually, number are only handled for the _ds/defs_ detection (where I need the actual values). The instructions just consider everything a number (except for registers, etc.); that's way it seems to be handling that format correctly ^_^

New nigthly build: https://github.com/theNestruo/z80-asm-meter-vscode/suites/1591887799/artifacts/28918673

**Comment by gougoutt** [comment]
Perfect :-)

**Comment by theNestruo** [comment]
Published! It should be available in a few minutes
