### ISSUE TITLE
ex af,af' parsing issue (Sjasm alternate syntax)

### ISSUE THREAD

**Issue by jltursan** [theNestruo/z80-asm-meter-vscode#74]
The mnemonic "ex af,af" is no more a valid one and now a strict syntax, "ex af,af'" (notice the ending single quote) is needed to be metered.
Since long time, none of my code uses the "strict" version as the single quote has been always problematic with other editors and their syntax highlihgtning schemes; so I wonder, it's definitely a bug or it's really on purpose?

**Comment by theNestruo** [comment]
Hi, jltursan!

Is that happening since v2.1.0? I think you are using SjASMPlus and one configuration property was renamed:

> ## 2.1.0
> 
> - Improved support for SjASMPlus alternate syntax (such as `EXA`)
> - Configuration property ~~`sjasmplusFakeInstructions`~~ renamed to `sjasmplus`

Can you check your `settings.json` and try again with the property name updated?
`ex af,af'`, `ex af, af`, `ex af`, and `exa` are all valid syntax for that instruction with `"z80-asm-meter.sjasmplus": true`.

Thank you!

**Comment by jltursan** [comment]
Solved!. Setting "z80-asm-meter.sjasmplus": true did the trick!
