### ISSUE TITLE
Could you add the ZX Next opcodes

### ISSUE THREAD

**Issue by maziac** [theNestruo/z80-asm-meter-vscode#9]

**Comment by theNestruo** [comment]
ZX Next is not on my current plans, sorry

**Comment by maziac** [comment]
OK. (That's a pity)

**Comment by theNestruo** [comment]
Well, it is not on my plans for the same reason R800 isn't there either... I don't use it, and barely know it, so **for me** it doesn't add value to the extension... and will probably add headaches to me :)

I think it would be difficult and time-consuming to troubleshoot problems with the R800/ZX Next opcodes, as I don't use them, and the workflow would be some user notifying a problem in an issue, me blindly solving it, publishing a new version, etc. For example: I'm not in the ZX Next scene, so I don't know where to look for a reliable instruction set...
Additionaly, I don't want the extension to grow into a configuration-hell: what should "new" instructions show for Z80+M1 timing? NOP timing? What about incompatible instructions (such as undocumented Z80 opcodes repurposed in the R800)? What about new instructions being falsely detected for users that use vanilla Z80?
Also, I'm not proficient coding VSCode extensions and TypeScript in general (this is my first time!), so everything above will take me more time than desired.

Those points make me reluctant for adding Z80-extended processors to the extension... but otherwise, adding more instructions is just a matter of adding them to the `src/z80InstructionSetRawData.ts` file (that should be relatively easy!)
So if anyone is willing to support R800, ZX Next, or other Z80-extended processor... please feel free to fork this extension, add the missing opcodes to that file (and conveniently drop Z80+M1 and NOP timing support, as those may not longer make any sense).
I honestly think having separate extensions for them is a better solution.

:)

**Comment by maziac** [comment]
Hi,

I now put a hover provider extension together that uses your z80 parser at the heart.
Please see:
https://github.com/maziac/z80-instruction-set

**Comment by theNestruo** [comment]
Z80N support added. Please check the latest version (1.0.0).

Also: if your extension uses my Z80 parser, please check this issue: https://github.com/theNestruo/z80-asm-meter-vscode/issues/17 and this commit: https://github.com/theNestruo/z80-asm-meter-vscode/commit/15281b30037697788131ac8cbfed0101fa2c0a27. Namely:
- a pair of values wrong in `src/z80InstructionSetRawData.ts`,
- and wrong parsing of instructions containing `IXh`, `IXl`, `IYh` or `IYl` in `src/z80instruction.ts`

(sorry about the commit mixing up unrelated changes)

**Comment by maziac** [comment]
Thanks for letting me know.
"a pair of values wrong in src/z80InstructionSetRawData.ts,": Do you know what that was?
(A diff with my version is not easily possible anymore.)

**Comment by theNestruo** [comment]
Yes, of course:
```
[ "LD IXh,n", "11", "13", "4", "DD 26 n", "2" ],
[ "LD IXl,n", "11", "13", "4", "DD 2E n", "2" ],
[ "LD IYh,n", "11", "13", "3", "FD 26 n", "2" ],
[ "LD IYl,n", "11", "13", "4", "FD 2E n", "2" ],
```
These four instructions mistakenly had a size of 2 bytes, when they are 3 bytes long (as it can be seen in their opcodes).

**Comment by maziac** [comment]
Thanks.
