### ISSUE TITLE
Can we associate this with .asm files too?

### ISSUE THREAD

**Issue by bengalack** [theNestruo/z80-asm-meter-vscode#91]
Would be great to use this on the files generated from SDCC.

**Comment by theNestruo** [comment]
Hi, Bengalack!
Registering the language ID reported by VS Code in those files in the setting `z80-asm-meter.languageIds` should enable the extension.

**Comment by bengalack** [comment]
Could you give me an example, because I can't get this to work. There is nothing there in the first place, it just magically work on some extensions.

My section now looks like this, but no luck:

```
		"z80-asm-meter": {
			"aliases": [
				"Z80 Assembly"
			],
			"filenames": [],
			"extensions": [],
			"lineComments": [],
			"blockComments": [],
			"blockStrings": [],
			"languageIds": [ "s", "asm" ]
		},
```

**Comment by theNestruo** [comment]
Yes, no problem.

Open one of the files and check which language is VS Code reporting for that kind of files in the status bar. Then, use the _"Change Language Mode"_ command (default binding: `CTRL+K M`) and look for the language to find the actual **language ID**:
![image](https://user-images.githubusercontent.com/12213477/190858454-adc7df39-b0c5-471a-839f-9252bbf8b180.png)
![image](https://user-images.githubusercontent.com/12213477/190858536-d68be2b4-d82a-471e-bf97-2ea60d7b22d8.png)
![image](https://user-images.githubusercontent.com/12213477/190858582-8c6d32cc-14cf-42e7-81bf-cf61b4c08e67.png)

Then, open your settings, look for "Z80 Assembly meter settings", section "Language Ids", and click in "Edit in settings.json". That will add the `z80-asm-meter.languageIds` setting to your _settings.json_:
![image](https://user-images.githubusercontent.com/12213477/190858701-c048020b-f7fc-439e-a250-449900a1c834.png)
![image](https://user-images.githubusercontent.com/12213477/190858863-fb61f1bf-1303-4467-9f7f-94d5c2c968a1.png)

Add the language ID, save, and automatically Z80 Assembly meter will start metering that kind of files. For the sake of the example, I've added "markdown" here:
![image](https://user-images.githubusercontent.com/12213477/190859021-1c5f2c0d-0f17-4d31-908b-aada9be447b6.png)

---

Alternatively, if you files ("*.s", I guess) are detected as "plain text" (i.e.: no other extension is "claiming" to know what are those file), you can use the `files.associations` setting to associate the extension to the Z80 Assembly language (id: `z80-asm-meter`). 
![image](https://user-images.githubusercontent.com/12213477/190859223-13827826-e285-42e1-85eb-554c25ad19fa.png)
This is not ideal because you won't have syntax highlighting, symbols, etc., as those are provided by other extensions (such as Z80 Macro-Assembler). Also, that's the reason why Z80 Assembly meter uses the `z80-asm-meter.languageIds` setting: to work together with anyone's favourite Z80 extension :)

**Comment by bengalack** [comment]
Wow thanks. This works now. And it has always annoyed me that I couldn't get inline asm to work inside c-files. Now it does. Thanks again!

**Comment by theNestruo** [comment]
I'm glad it worked :)
Please let me know the language IDs you have set in `z80-asm-meter.languageIds` so I can add a small section for SDCC users in the readme/F.A.Q. Thanks!

**Comment by bengalack** [comment]
After restarting visual c, it now only works on .asm and .c,. NOT .s. :( And if I add "s" to this: 

	"z80-asm-meter.languageIds": [ "s", "c", "asm" 
	
	],

it does not work either. Wierd

**Comment by bengalack** [comment]
Actually, only .c files really work with both syntax highlighting + asm-meter now :( The system seems confused. Seem like it remembers individual files as well, not only "per extension".

**Comment by theNestruo** [comment]
> After restarting visual c, it now only works on .asm and .c,. NOT .s. :( And if I add "s" to this:
> 
> ```
> "z80-asm-meter.languageIds": [ "s", "c", "asm" 
> 
> ],
> ```
> 
> it does not work either. Weird


> Actually, only .c files really work with both syntax highlighting + asm-meter now :( The system seems confused. Seem like it remembers individual files as well, not only "per extension".

_.c_ files probably have C language (id: `c`), while _.asm_ and _.s_ have assembly language, but the language ID is **not** `asm` or `s`, but depends on your extensions (it will be `z80-macroasm`, `pasmo`, or something like that).
The `"z80-asm-meter.languageIds"` setting does not use extensions but language IDs (`c` works because both the extension and the language ID match).

If your _.asm_ and _.s_ are shown as "plain text" in the status bar, that means no extension is giving them a language. You can tell VS Code to give them a language using the setting:
```
  "files.associations": {
    "*.asm": "z80-asm-meter",
    "*.s": "z80-asm-meter",
  ],
```

**Comment by bengalack** [comment]
Ok, thanks again. Now things work!

.asm and .s is "Z80 Macro-Assembler",  and my setting is now:


	"z80-asm-meter.languageIds": [ "c", "z80-macroasm",
	
	],

And it works like a charm :)
